name: "Package"
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Load environment variables
        run: |
          echo "CRX_ID=${{ secrets.CRX_ID }}" >> $GITHUB_ENV
          echo "CRX_KEY=${{ secrets.CRX_KEY }}" >> $GITHUB_ENV
      - name: Build and package the extension for all targets
        run: pnpm export
      - name: Create GitHub Release with zip files
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
